# Usar una imagen base oficial
FROM ubuntu:latest

# Definir el directorio de trabajo
WORKDIR /app

# Copiar un archivo de prueba
COPY archivo_prueba.txt /app/

# Comando por defecto al iniciar el contenedor
CMD ["ls", "-l", "/app"]
